# .travis.yml
sudo: required

language: node_js

node_js:
  - '0.12'
  - '4'
  - '5'
  - '6'

before_install:
  - docker pull wnameless/oracle-xe-11g
  - docker run --name db -d -p 1521:1521 -e ORACLE_ALLOW_REMOTE=true wnameless/oracle-xe-11g

before_script:
  - psql -c 'create database knex_test;' -U postgres
  - mysql -e 'create database knex_test;'

after_script:
  - npm run-script coveralls

notifications:
  email: false

env:
  - CXX=g++-4.8 KNEX_TEST_TIMEOUT=60000

addons:
  postgresql: '9.4'
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - gcc-4.8

services:
  - docker
